"""Contract-agnostic agreement compilation and verification primitives."""

from .bundle import (
    AgreementBundle,
    AgreementDocument,
    DocumentRelation,
    DocumentRelationType,
    applicable_documents,
    resolved_bundle_text,
)
from .capabilities import (
    EvidenceCapability,
    EvidenceSourceDescriptor,
    VerificationPlan,
    build_verification_plan,
)
from .legacy import legacy_rule_program_to_agreement_ir
from .models import (
    AgreementIR,
    AutomationClass,
    ClauseCoverage,
    CommercialClaim,
    CompilerDiagnostic,
    ConformanceReport,
    EvidenceArtifact,
    EvidenceAuthority,
    Expression,
    Fact,
    Norm,
    NormType,
    ObligationStatus,
    Observation,
    ProofRequirement,
    ProvenanceEdge,
    SettlementLine,
    TruthValue,
    WorkGraph,
)
from .runtime import (
    EvaluationContext,
    calculate_settlement,
    evaluate_expression,
    evaluate_norm,
)

__all__ = [
    "AgreementBundle",
    "AgreementDocument",
    "AgreementIR",
    "AutomationClass",
    "ClauseCoverage",
    "CommercialClaim",
    "CompilerDiagnostic",
    "ConformanceReport",
    "DocumentRelation",
    "DocumentRelationType",
    "EvaluationContext",
    "EvidenceArtifact",
    "EvidenceAuthority",
    "EvidenceCapability",
    "EvidenceSourceDescriptor",
    "Expression",
    "Fact",
    "Norm",
    "NormType",
    "ObligationStatus",
    "Observation",
    "ProofRequirement",
    "ProvenanceEdge",
    "SettlementLine",
    "TruthValue",
    "VerificationPlan",
    "WorkGraph",
    "applicable_documents",
    "build_verification_plan",
    "calculate_settlement",
    "evaluate_expression",
    "evaluate_norm",
    "legacy_rule_program_to_agreement_ir",
    "resolved_bundle_text",
]
