#!/usr/bin/env python3
"""Generate inspectable production-shaped demo source files.

The files are representative samples, while manifest.json records the aggregate
volumes generated by the deterministic ingestion pipeline. The application uses
the same pipeline directly during demo reset.
"""

from __future__ import annotations

import csv
import json
import os
import sys
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "backend"))

from app.fixtures.demo import scenario_fixture
from app.ingestion.demo_pipeline import build_ingestion_bundle

OUTPUT = ROOT / "demo-data"

PATHS = {
    "vendor_claim_manifest": OUTPUT / "vendor" / "june-claim-manifest.csv",
    "vendor_agent_log": OUTPUT / "vendor" / "agent-execution-log.jsonl",
    "support_desk": OUTPUT / "customer" / "support-events.jsonl",
    "payment_processor": OUTPUT / "customer" / "payment-events.jsonl",
    "product_operations": OUTPUT / "customer" / "product-events.jsonl",
    "billing_ledger": OUTPUT / "customer" / "billing-ledger.csv",
    "identity_map": OUTPUT / "customer" / "customer-account-map.csv",
    "contract_documents": OUTPUT / "contract" / "order-form-extract.json",
}


def csv_value(value: object) -> object:
    if isinstance(value, (dict, list)):
        return json.dumps(value, sort_keys=True)
    return value


def write_csv(path: Path, rows: list[dict[str, object]]) -> None:
    fields = sorted({key for row in rows for key in row})
    with path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=fields)
        writer.writeheader()
        for row in rows:
            writer.writerow({key: csv_value(row.get(key, "")) for key in fields})


def main() -> None:
    os.makedirs(OUTPUT, exist_ok=True)
    for path in PATHS.values():
        path.parent.mkdir(parents=True, exist_ok=True)

    bundle = build_ingestion_bundle(scenario_fixture("headline"), "headline")
    grouped: dict[str, list[dict[str, object]]] = defaultdict(list)
    for raw in bundle.raw_samples:
        grouped[raw.connector_id].append(raw.payload)

    for connector_id, path in PATHS.items():
        rows = grouped.get(connector_id, [])
        if path.suffix == ".csv":
            write_csv(path, rows)
        elif path.suffix == ".jsonl":
            path.write_text(
                "".join(json.dumps(row, sort_keys=True) + "\n" for row in rows),
                encoding="utf-8",
            )
        else:
            payload: object = rows[0] if len(rows) == 1 else rows
            path.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")

    manifest = {
        "disclosure": "All records are synthetic and generated deterministically.",
        "purpose": "Representative source-system exports used to demonstrate the production ingestion path.",
        "aggregate": {
            "claims_received": bundle.stats.claims_received,
            "direct_matches": bundle.stats.direct_matches,
            "secondary_matches": bundle.stats.secondary_matches,
            "unresolved_matches": bundle.stats.unresolved_matches,
            "source_records_received": bundle.stats.source_records_received,
            "source_records_normalized": bundle.stats.source_records_normalized,
            "source_records_rejected": bundle.stats.source_records_rejected,
        },
        "sources": [
            {
                "id": snapshot.connector.id,
                "name": snapshot.connector.name,
                "demo_file": str(PATHS[snapshot.connector.id].relative_to(ROOT)),
                "representative_records_in_file": len(grouped.get(snapshot.connector.id, [])),
                "aggregate_records_received": snapshot.records_received,
                "production_method": snapshot.connector.production_method,
                "trust_boundary": snapshot.connector.trust_boundary,
            }
            for snapshot in bundle.connectors
        ],
    }
    (OUTPUT / "manifest.json").write_text(
        json.dumps(manifest, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )


if __name__ == "__main__":
    main()
